version: '3'

services:

    client:
        image: amazoncorretto:11-alpine
        restart: always
        network_mode: host
        volumes:
          - ./:/client
        working_dir: /client/bin
        command: java -jar client.jar
