version: '3'

services:

    client:
        image: ibm-semeru-runtimes:open-11-jre
        restart: always
        network_mode: host
        volumes:
          - ./:/client
        working_dir: /client/bin
        command: java -jar client.jar
